main/urls.py
from django.urls import path
from django.conf.urls import url, include

from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name='index'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('transfer/', views.money_transfer, name='money_transfer'),
    path('payments/', views.service_payment, name='service_payment'),
    path('history/', views.history, name='history'),
    path('deposits/', views.deposits, name='deposits'),
    path('depositmoney/', views.deposit_money, name='depositmoney'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('logout/', views.logout, name='logout'),
    path('mybank/', views.myBank, name='mybank'),
]

online_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models


# Create your models here.
# image = models.ImageField(upload_to='club_images', blank=True, null=True)

class Customer(models.Model):
    customer_login = models.CharField(max_length=25, default="")
    customer_password = models.CharField(max_length=25, default="")
    customer_name = models.CharField(max_length=25)
    customer_surname = models.CharField(max_length=25)


class Service_type(models.Model):
    service_type_name = models.CharField(max_length=50)


class Account(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    balance = models.IntegerField(default=0)
    number = models.IntegerField(default=0)


class Deposits(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateTimeField()
    balance = models.IntegerField(default=0)


class Service(models.Model):
    service_name = models.CharField(max_length=50)
    service_desc = models.CharField(max_length=255)
    amount = models.IntegerField(default=0)
    service_type = models.ForeignKey(Service_type, on_delete=models.CASCADE)


class Account_type(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    desc = models.CharField(max_length=255)


class Transfer(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='%(class)ssender_account')
    amount = models.IntegerField(default=0)
    transaction_type = models.BooleanField()
    receiver = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='%(class)sreceiver_account')
    transaction_date = models.DateTimeField(auto_now_add=True)

main/views.py
import random
from datetime import datetime

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import Customer, Account, Transfer, Deposits


# Create your views here.
def index(request):
    return render(request, "index.html", {

    })


def registration(request):
    if request.method == 'POST':
        login = request.POST.get("login", None)
        password = request.POST.get("password", None)
        name = request.POST.get("name", None)
        surname = request.POST.get("surname", None)

        if not password or not login or not name or not surname:
            return HttpResponse("reg data not given")

        customer = Customer(customer_login=login, customer_password=password, customer_name=name,
                            customer_surname=surname)
        n = random.randint(100, 999)

        while Account.objects.filter(number=n).exists():
            n = random.randint(100, 999)

        account = Account(customer=customer, balance=0, number=n)
        customer.save()
        account.save()

        return redirect(reverse('main:login'))

    else:
        return render(request, "registration.html", {})


def myBank(request):
    if request.session.get("user_id") is not None:
        current_account_id = int(request.session.get("user_id"))
        account = Account.objects.get(id=current_account_id)

        deposit_customer = Customer.objects.get(id=current_account_id)

        deposit_objects = Deposits.objects.filter(customer=deposit_customer)
        if len(deposit_objects) == 0:
            deposit_info = "no deposit account"
        else:
            deposit = Deposits.objects.get(customer=deposit_customer)
            deposit_info = str(deposit.balance)

        return render(request, "mybank.html", {"account": account,"deposit_info": deposit_info})
    else:
        return redirect(reverse('main:index'))


def deposits(request):
    if request.session.get("user_id") is not None:

        return render(request, "deposit.html", {})
    else:
        return redirect(reverse('main:index'))


def deposit_money(request):
    if request.method == "POST":
        current_account_id = int(request.session.get("user_id"))
        amount = int(request.POST.get("amount", None))
        date = datetime.now()
        try:
            deposit_account = Account.objects.get(id=current_account_id)
            deposit_customer = Customer.objects.get(id=current_account_id)
            if deposit_account.balance >= amount:
                deposit_objects = Deposits.objects.filter(customer=deposit_customer)
                if len(deposit_objects) == 0:
                    deposit = Deposits(customer=deposit_customer, date=date, balance=amount)
                    deposit.save()
                    deposit_account.balance = deposit_account.balance - amount
                    deposit_account.save()
                    return redirect(reverse('main:mybank'))
                else:
                    print("false")
                    deposit = Deposits.objects.get(customer=deposit_customer)
                    deposit.balance += amount
                    deposit.save()
                    deposit_account.balance = deposit_account.balance - amount
                    deposit_account.save()
                    return redirect(reverse('main:mybank'))
        except:
            print("something went wrong")
            return redirect(reverse('main:mybank'))


def withdraw(request):
    if request.method == "POST":
        current_account_id = int(request.session.get("user_id"))
        amount = int(request.POST.get("amount", None))
        withdraw_date = datetime.now()
    try:

        deposit_customer = Customer.objects.get(id=current_account_id)
        deposit_account = Account.objects.get(id=current_account_id)
        deposit_objects = Deposits.objects.filter(customer=deposit_customer)
        if len(deposit_objects) == 0:
            print("user don't have deposit account")
            return redirect(reverse('main:mybank'))
        else:
            deposit = Deposits.objects.get(customer=deposit_customer)
            deposit.balance = deposit.balance - amount
            difference = withdraw_date - deposit.date.replace(tzinfo=None)
            if difference.days >= 30:
                print("true")
                multiplier = difference.days/30
                reward = amount + ((amount/100)*(9*multiplier))
                deposit_account.balance += reward
                deposit.date = datetime.now()
                deposit_account.save()
            else:
                print("false")
                deposit_account.balance += amount
                deposit_account.save()

            deposit.save()

            return redirect(reverse('main:mybank'))
    except:
        print("something went wrong")
        return redirect(reverse('main:mybank'))


def login(request):
    if request.method == "POST":
        login = request.POST.get("login", None)
        password = request.POST.get("password", None)
        try:
            customer = Customer.objects.get(customer_login=login, customer_password=password)
            print("trying to find customer")
            if customer:
                print("customer not null")
                account = Account.objects.filter(customer=customer)[0]
                request.session["user_id"] = account.id
                request.session["user_number"] = account.number
                return redirect(reverse('main:mybank'))
        except:
            print("something went wrong")
            return render(request, "login.html", {})
    else:
        return render(request, "login.html", {})


def logout(request):
    del request.session["user_id"]
    del request.session["user_number"]
    return redirect(reverse('main:index'))


def money_transfer(request):
    print("money transfer is starting")
    if request.method == "POST":
        current_account_id = int(request.session.get("user_id"))
        print(current_account_id)
        receiver_number = request.POST.get("receiver_number", None)
        amount = int(request.POST.get("amount", None))
        try:
            sender_account = Account.objects.get(id=current_account_id)
            receiver_account = Account.objects.get(number=receiver_number)
            if receiver_account:
                if sender_account.balance >= amount:
                    transfer = Transfer(account=sender_account, amount=amount, transaction_type=True,
                                        receiver=receiver_account)
                    print("transfer: ")
                    print(transfer)
                    transfer.save()
                    sender_account.balance = sender_account.balance - amount
                    print(sender_account.balance)
                    sender_account.save()

                    print("receiver_account found!")
                    receiver_account.balance = receiver_account.balance + amount

                    receiver_account.save()
                    return redirect(reverse('main:mybank'))
        except:
            print("something went wrong")
            return redirect(reverse('main:money_transfer'))
    else:
        if request.session.get("user_id") is not None:
            return render(request, "transfer.html", {})
        else:
            return render(request, "login.html", {})


def service_payment(request):
    print("service payment is starting")
    if request.method == "POST":
        current_account_id = int(request.session.get("user_id"))
        amount = int(request.POST.get("amount", None))
        service_name = request.POST.get("service_name", None)
        try:
            sender_account = Account.objects.get(pk=current_account_id)
            print(sender_account)

            if sender_account.balance >= amount:
                sender_account.balance = sender_account.balance - amount
                print(sender_account.balance)
                sender_account.save()

                return redirect(reverse('main:mybank'))
        except:
            print("something went wrong")
            return redirect(reverse('main:mybank'))
    else:
        if request.session.get("user_id") is not None:
            return render(request, "payments.html", {})
        else:
            return render(request, "login.html", {})


def history(request):
    print("history is starting")
    if request.method == "POST":
        print("hello")
    else:
        if request.session.get("user_id") is not None:
            current_account_id = int(request.session.get("user_id"))
            current_user_account = Account.objects.get(id=current_account_id)

            user_transfers = Transfer.objects.filter(account=current_user_account)

            return render(request, "history.html", {"transfers": user_transfers})
        else:
            return render(request, "login.html", {})

main/templates/base.html
{% load static %}

{% block links %}

    <head>

    

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bank application</title>

        <link rel="stylesheet" href="{%static 'css/index.css'%}" />
        
        
        {% block styles %}
          <h1 class="header">Aitu Bank</h1>
        {% endblock %}
    </head>
{% endblock %}



{% block body%}
    
    
{% endblock %}


{%block scripts%}
{%endblock%}

main/templates/deposit.html
{% extends "base.html" %}
{% load static%}

{%block styles %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">

{% endblock %}


{% block body %}
<div class="topnav">
    <a href="/mybank" >Home</a>
    <a href="/transfer">Transfer</a>
    <a href="/history">History</a>
    <a href="/payments" >Payments</a>
    <a href="/logout" style="float:right">Logout</a>
    </div>
    {% block content %}
    <form class="leftcolumn" method="post" action="{% url 'main:depositmoney'%}">
            {% csrf_token %}
            <h2>Deposit form</h2>
            <label><b>Deposit percentage: 9%</b></label>
            <label><b>Amount</b></label>
            <input type="number" name="amount" placeholder="amount"> <br>
            <button type="submit">Send</button>
        </form>
        <form class="rightcolumn" method="post" action="{% url 'main:withdraw'%}">
            {% csrf_token %}
            <h2>Withdraw form</h2>
            <label><b>Amount</b></label>
            <input type="number" name="amount" placeholder="amount"> <br>
            <button type="submit">Send</button>
        </form>
        {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}

{%endblock%}

main/templates/history.html
{% extends "base.html" %}
{% load static%}

{%block styles %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">

{% endblock %}


{% block body %}
<div class="topnav">
    <a href="/mybank" >Home</a>
    <a href="/transfer">Transfer</a>
    <a href="/payments" >Payments</a>
    <a href="/deposits" >Deposits</a>
    <a href="/logout" style="float:right">Logout</a>
    </div>
    {% block content %}
        
    <h1>My transfers history:</h1>
        <div class="card" >
        <table>
                <tr>
                    <th>Receiver</th>
                    <th>Receiver's card number</th>
                    <th>Amount</th>
                    <th>Date</th>
                </tr>

    {% for transfer in transfers %}
        <tr>
            <td>{{ transfer.receiver.customer.customer_name }} {{ transfer.receiver.customer.customer_surname }} </td>
            <td>{{ transfer.receiver.number }}</td>
            <td>{{ transfer.amount }}</td>
            <td>{{ transfer.transaction_date }}</td>
        </tr>
    {% endfor %}
             </table>
        </div>

    {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}
    
{%endblock%}

main/templates/index.html
{% extends "base.html" %}
{% load static%}

{%block styles %}

    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">
{% endblock %}


{% block body %}
    <div class="header">
    <h1>Python Banking</h1>
    <p>An online banking system made on python.</p>
    </div>

  <div class="topnav">
    <a href="/registration" style="float:right">Sign up</a>
    <a href="/login" style="float:right">Sign in</a>
    </div>


    {% block content %}

        {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}
    
{%endblock%}

main/templates/login.html
{% extends "base.html" %}
{% load static%}

{%block styles %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">

{% endblock %}


{% block body %}
  <div class="topnav">

</div>
    {% block content %}
        <form method="post" action="{% url 'main:login'%}">
        <div class="container">
            {% csrf_token %}
            <h2>Login Form</h2>
            <label><b>Login</b></label>
            <input id="name" placeholder="Enter login" type="text" name="login"><br>
            <label><b>Password</b></label>
            <input id="name" type="password" placeholder="Enter password" name="password"><br>
            <input type="submit" value="OK">
            </div>
        </form>
        {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}
    
{%endblock%}

main/templates/mybank.html
{% extends "base.html" %}
{% load static%}

{%block styles %}

    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">
{% endblock %}


{% block body %}

  <div class="topnav">
    <a href="/history" >History</a>
    <a href="/transfer">Transfer</a>
    <a href="/payments" >Payments</a>
    <a href="/deposits">Deposits</a>
    <a href="/logout" style="float:right">Logout</a>
    </div>
    {% block content %}
        <div class="row">
    <div class="leftblock">
        <div class="balance" style="background: white">
            <div>Current user</div>
            <div>{{ account.customer.customer_name }} {{ account.customer.customer_surname }}</div>
        </div>

        <div class="balance">
            <div>Available</div>
            <div>{{ account.balance }}</div>
        </div>

        <div class="balance" style="background-color: silver">
            <div>Deposite balance</div>
            <div>{{ deposit_info }}</div>
        </div>

        <div class="balance" style="background: grey">
            <div>Card number</div>
            <div>{{ account.number }}</div>
        </div>


        </div>
        </div>
        {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}
    
{%endblock%}

main/templates/payments.html
{% extends "base.html" %}
{% load static%}

{%block styles %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">

{% endblock %}


{% block body %}
<div class="topnav">
    <a href="/mybank" >Home</a>
    <a href="/history">History</a>
    <a href="/transfer" >Transfer</a>
    <a href="/deposits" >Deposits</a>
    <a href="/logout" style="float:right">Logout</a>
    </div>
    {% block content %}
        <form method="post" action="{% url 'main:service_payment'%}">
            {% csrf_token %}
            <input hidden  name="service_name" value="Internet">
            <input hidden   name="amount" value="200">
            <button type="submit">Internet</button>
        </form>
        {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}
    
{%endblock%}

main/templates/registration.html
{% extends "base.html" %}
{% load static%}

{%block styles %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">

{% endblock %}


{% block body %}

    {% block content %}
        <form method="post" action="{% url 'main:registration'%}">
            {% csrf_token %}
            <h2>Register Form</h2>
            <label><b>Name</b></label>
            <input id="name" type="text" name="name" placeholder="name"><br>
            <label><b>Surname</b></label>
            <input id="surname" type="text" name="surname" placeholder="surname"><br>
            <label><b>Login</b></label>
            <input id="login" type="text" name="login" placeholder="login"><br>
            <label><b>Password</b></label>
            <input id="password" type="password" name="password" placeholder="password"><br>
            <input type="submit" value="OK">
        </form>
        {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}
    
{%endblock%}

main/templates/transfer.html
{% extends "base.html" %}
{% load static%}

{%block styles %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}">

{% endblock %}


{% block body %}
<div class="topnav">
    <a href="/mybank" >Home</a>
    <a href="/history">History</a>
    <a href="/payments" >Payments</a>
    <a href="/logout" style="float:right">Logout</a>
    </div>
    {% block content %}
        <form method="post" action="{% url 'main:money_transfer'%}">
            {% csrf_token %}
            <h2>Transfer form</h2>
            <label><b>Receiver number</b></label>
            <input type="text" name="receiver_number" placeholder="receiver's card number"> <br>
            <label><b>Amount</b></label>
            <input type="number" name="amount" placeholder="amount"> <br>
            <button type="submit">Send</button>
        </form>
        {% endblock %}
    {% block footer %}
        <div class="footer">
    <h2>Footer</h2>
</div>
        {% endblock %}
{% endblock %}


{%block scripts%}
    
{%endblock%}